/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Containers;

import Controlador.Game;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;

/**
 * 
 * @author Maria y Karol
 */
public class GamePanel extends javax.swing.JPanel implements Container{
    
    /**
     * Knows the game to real implement its graphic part
     */
    private Game game ;

 
    /**
     * Define the game
     * @param game 
     */
    public void setGame(Game game) {
        this.game = game;
        game.setContainer(this);
    }
    
    /**
     * Draw the game
     * @param g 
     */
     @Override
    public void paint(Graphics g)
    {
        if(game != null)
        {
            game.draw(g);
            game.paint(g);
        }
        else{  System.err.println("[GAMEPANEL.PAINT] Controller game is null!");}
    }
    
    /**
     * Update the object in the View
     */
    @Override
    public void refresh() {this.repaint(); }

    /**
     * Get the measurements of the game panel
     * @return Rectangle object that is used in the graph part
     */
    @Override
    public Rectangle getBoundaries() { return this.getBounds();}
    
    /**
     * Get the needed size of the object
     * @return the size of the game object
     */
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(game.getWidth(),game.getHeight());  }
    
    /**
     * Creates new form GamePanel
     */
    public GamePanel() { initComponents();}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
