/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Containers;

import Controlador.Game;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Rectangle;

/**
 *
 * @author maria
 */
public class GamePanel extends javax.swing.JPanel implements Container{

    private Game game ;

 
    
    public void setGame(Game game) {
        this.game = game;
        game.setContainer(this);
        
    }
    
    /**
     * 
     * @param g 
     */
     @Override
    public void paint(Graphics g)
    {
        if(game != null)
        {
            game.draw(g);
            game.paint(g);
        }
        else
            System.err.println("[GAMEPANEL.PAINT] World is null!");
    }
    
    /**
     * 
     */
    @Override
    public void refresh() {
        
        this.repaint();
        
      
    }

    /**
     * 
     * @return 
     */
    @Override
    public Rectangle getBoundaries() {
        
       return getBounds();
     
    }
    /**
     * 
     */
    @Override
    public Dimension getPreferredSize() {
        return new Dimension(game.getWidth(),game.getHeight());
    }
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
