/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Windows 10
 */
public class Instruction extends javax.swing.JDialog {

    private boolean state;
    
    
    public void open()
    {
        this.setLocationRelativeTo(null);
         instruction();
        this.setVisible(true);
          
        state=false;
    }
    
    public void instruction()
    {
        String texto="<hmtl><p> \"\n" +
"                + \"antibiotico entraras al cuerpo humano , pasando por tres tres niveles , primero el estomago, luego los pulmones y por ultimo el corazon,para eso deberas\"\n" +
"                + \"pelear con bacterias bloqueadoras y que ponen cajas, explotandolas con las bombas de infinita cantidad oprimiendo la tecla b , tambien debes romper cajas para lamacenar puntos y continuar con \"\n" +
"                + \"el siguiente nivel , tienes una vida de 100 puntos></p></html>";
        String texto2 = "<html>En un mundo donde las enfermedades estan por todos lados<P><html>,ahora tu eres el heroe que salvara a las personas , como"
                + "<html> antibiotico entraras al cuerpo humano , pasando por tres tres niveles , primero el estomago, luego los pulmones y por ultimo el corazon,para eso deberas<p>pelear con bacterias bloqueadoras y que ponen cajas, explotandolas con las bombas de infinita cantidad oprimiendo la tecla b , tambien debes romper cajas para lamacenar puntos y continuar con \"\n" +
"                 \"el siguiente nivel , tienes una vida de 100 puntos";
        this.jLabel1.setText(texto2);
    }

    public boolean isState() {
        return state;
    }
    
    
    /**
     * Creates new form Instruction
     */
    public Instruction(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlInstruction = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlInstruction.setText("        INSTRUCTION");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jlInstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jlInstruction, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        state=true;
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlInstruction;
    // End of variables declaration//GEN-END:variables
}
