/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author maria
 */
public class LevelGame extends javax.swing.JDialog {

    private boolean state; 
    private int option;

    public boolean isState() {
        return state;
    }

    public int getOption() {
        return option;
    }

    
    public void open(int level)
    {
        switch(level)
        {
            case 0:
                enableFirstLevel();
                break;
            case 1:
                enableSecondLevel();
                break;
            case 2:
                enableThirdLevel();
                break;
        }
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    
    /**
     * 
     */
    public void enableFirstLevel()
    {
        btLung.setEnabled(true);
        btHeart.setEnabled(true);
    }
    
    /**
     * 
     */
    public void enableSecondLevel()
    {
        btLung.setEnabled(true);
    }
    
    /**
     * 
     */
    public void enableThirdLevel()
    {
        btLung.setEnabled(true);
        btHeart.setEnabled(true);
    }
    /**
     * Creates new form LevelGame
     * @param parent
     * @param modal
     */
    public LevelGame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btStomach = new javax.swing.JButton();
        btLung = new javax.swing.JButton();
        btHeart = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btStomach.setBorderPainted(false);
        btStomach.setContentAreaFilled(false);
        btStomach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStomachActionPerformed(evt);
            }
        });
        getContentPane().add(btStomach, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 60, 60));

        btLung.setBorderPainted(false);
        btLung.setContentAreaFilled(false);
        btLung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLungActionPerformed(evt);
            }
        });
        getContentPane().add(btLung, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 40, 90));

        btHeart.setBorderPainted(false);
        btHeart.setContentAreaFilled(false);
        btHeart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHeartActionPerformed(evt);
            }
        });
        getContentPane().add(btHeart, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 40, 60));

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LevelGame.jpg"))); // NOI18N
        getContentPane().add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btStomachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStomachActionPerformed
       option=0;
       state = true;
       this.dispose();
    }//GEN-LAST:event_btStomachActionPerformed

    private void btLungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLungActionPerformed
       option=1;
       state = true;
       this.dispose();
    }//GEN-LAST:event_btLungActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      state=false;
      this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btHeartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHeartActionPerformed
       option=2;
       state=true;
       this.dispose();
    }//GEN-LAST:event_btHeartActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton btHeart;
    private javax.swing.JButton btLung;
    private javax.swing.JButton btStomach;
    private javax.swing.JButton btnBack;
    // End of variables declaration//GEN-END:variables
}
